from . import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    designation = db.Column(db.String(100), nullable=False)
    about = db.Column(db.Text, nullable=False)
    phone = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(100), nullable=False)
    website = db.Column(db.String(100), nullable=False)
    location = db.Column(db.String(100), nullable=False)
    facebook = db.Column(db.String(100), nullable=False)
    instagram = db.Column(db.String(100), nullable=False)
    linkedin = db.Column(db.String(100), nullable=False)
    twitter = db.Column(db.String(100), nullable=False)
    profile_image_url = db.Column(db.String(200), nullable=True)
    show_services = db.Column(db.Boolean, default=False)
    service1_title = db.Column(db.String(100), nullable=True)
    service1_description = db.Column(db.Text, nullable=True)
    service2_title = db.Column(db.String(100), nullable=True)
    service2_description = db.Column(db.Text, nullable=True)
    service3_title = db.Column(db.String(100), nullable=True)
    service3_description = db.Column(db.Text, nullable=True)
    service4_title = db.Column(db.String(100), nullable=True)
    service4_description = db.Column(db.Text, nullable=True)
