"""Add uuid to User model

Revision ID: 1cf4a812dcda
Revises: 
Create Date: 2024-07-06 10:35:04.494627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf4a812dcda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('facebook', sa.String(length=100), nullable=False),
    sa.Column('instagram', sa.String(length=100), nullable=False),
    sa.Column('linkedin', sa.String(length=100), nullable=False),
    sa.Column('twitter', sa.String(length=100), nullable=False),
    sa.Column('profile_image_url', sa.String(length=200), nullable=True),
    sa.Column('show_services', sa.Boolean(), nullable=True),
    sa.Column('service1_title', sa.String(length=100), nullable=True),
    sa.Column('service1_description', sa.Text(), nullable=True),
    sa.Column('service2_title', sa.String(length=100), nullable=True),
    sa.Column('service2_description', sa.Text(), nullable=True),
    sa.Column('service3_title', sa.String(length=100), nullable=True),
    sa.Column('service3_description', sa.Text(), nullable=True),
    sa.Column('service4_title', sa.String(length=100), nullable=True),
    sa.Column('service4_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
